version: '3.8'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "mssql-server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd@123
    ports:
      - "1433:1433"
    networks:
      - vehiclescontrol-network

  vehiclescontrol-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "vehiclescontrol-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-server,1433;Database=VehiclesControlDB;User Id=sa;Password=Passw0rd@123;
    ports:
      - "5019:5019"
      - "7264:7264"
    depends_on:
      - mssql
    networks:
      - vehiclescontrol-network
    volumes:
      - ./src:/src

networks:
  vehiclescontrol-network:
    driver: bridge
